### ISSUE TITLE
Font area larger than Image area

### ISSUE THREAD

**Issue by robrao** [robrao/prolixor#15]
Traceback (most recent call last):
  File "img_creation.py", line 68, in <module>
    x_jitter = randint(0, int((im_w - dw) * 0.25)) * choice([-1, 1])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,-3, -3)

It appears sometimes Font width is larger than the image width causing the x_jitter randomizer to fail.

**Comment by robrao** [comment]
Resolved. #24
