### ISSUE TITLE
Character script randomly crashes

### ISSUE THREAD

**Issue by robrao** [robrao/prolixor#22]
Something related to random intergers not being able to be created for some ranges...

**Comment by robrao** [comment]
```
Traceback (most recent call last):
  File "img_creation.py", line 69, in <module>
    x_jitter = randint(0, int((im_w - dw) * 0.25)) * choice([-1, 1])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,-3, -3)
```

**Comment by robrao** [comment]
Can't have negative values in randrange().

Source of the problem is that font height or width (dh, dw) is large than image height or image width (im_h, im_w). This should never happens.

**Comment by robrao** [comment]
Issue is caused by multiplying `im_w_f` by 0.61, and multiplying `im_h_f` by 0.1

These multiplications were done to decrease the space of the image, because in most causes the image is much larger than the text inserted, but occasionally the image isn't much large and by decreasing the size further the text becomes larger than the image.

**Comment by robrao** [comment]
Before drawing text check the ratio of `txt_w/img_w` (txt_w will be the total width of all characters) and `txt_h/img_h` and then remove `(1 - (txt_w/img_w))/2` from _im_w_f_.

**Comment by robrao** [comment]
Is this really of concern? Why not just remove the reduction of the image size?
